apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.monitoring.prometheusScrape }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics.php
    prometheus.io/port: "80"
  {{- end }}
spec:
  selector:
    app: {{ include "snake-stack.fullname" . }}-backend
  ports:
    - name: http
      port: 80
      targetPort: http
