apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snake-stack.fullname" . }}-config
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
data:
  db-name: {{ .Values.config.dbName | quote }}
  db-host: {{ .Values.config.dbHost | quote }}
  db-port: {{ .Values.config.dbPort | quote }}
  cors-origin: {{ .Values.config.corsOrigin | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snake-stack.fullname" . }}-mysql-init
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Values.mysql.initSql | indent 4 }}
