apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snake-stack.fullname" . }}-frontend
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "snake-stack.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "snake-stack.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
