apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "snake-stack.fullname" . }}-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
