apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "snake-stack.fullname" . }}-mysql
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "snake-stack.fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "snake-stack.fullname" . }}-mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-config
                  key: db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-secret
                  key: mysql-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p\"$MYSQL_ROOT_PASSWORD\""]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
{{ toYaml .Values.mysql.resources | indent 12 }}
      volumes:
        - name: init-script
          configMap:
            name: {{ include "snake-stack.fullname" . }}-mysql-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.mysql.storage.storageClass }}
        storageClassName: {{ .Values.mysql.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.storage.size }}
