apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snake-stack.fullname" . }}-secret
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.credentials.rootPassword | quote }}
  mysql-user: {{ .Values.mysql.credentials.user | quote }}
  mysql-password: {{ .Values.mysql.credentials.password | quote }}
  app-jwt-secret: {{ .Values.config.appJwtSecret | quote }}
