prometheus:
  prometheusSpec:
    scrapeInterval: 30s

grafana:
  adminPassword: admin123
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.snake.local

alertmanager:
  enabled: true
