apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snake-backend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - snake
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics.php
      interval: 30s
