apiVersion: v1
kind: Secret
metadata:
  name: snake-secrets
  namespace: snake
type: Opaque
stringData:
  mysql-root-password: root_password
  mysql-user: snake_user
  mysql-password: snake_password
  app-jwt-secret: replace-with-strong-secret
