apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snake-stack.fullname" . }}-backend
  labels:
    {{- include "snake-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "snake-stack.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "snake-stack.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-config
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-secret
                  key: mysql-password
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-secret
                  key: app-jwt-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "snake-stack.fullname" . }}-config
                  key: cors-origin
          readinessProbe:
            httpGet:
              path: /healthz.php
              port: http
            initialDelaySeconds: 8
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz.php
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
